spring.application.name=SpringIntegrationExample
spring.profiles.active= dev
spring.profiles.include=application-${spring.profiles.active}.yaml

management.endpoints.web.exposure.include=mappings
management.endpoint.mappings.enabled=true

